/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Patern;

import java.io.File;

public class App {

    public static void main(String[] args) throws Exception {
        PaternEngine paternEngine = new PaternEngine();
        String operationHash = paternEngine.registerOperation(new File("operations/print.js"));
        Procedure procedure = new Procedure(new String[]{operationHash});
        String hash = paternEngine.registerProcedure(procedure);
        paternEngine.run(hash);
    }
}
